import java.io.*;
/**
 * KidCodeJavaFileGenerator
 * ------------------------
 * This class generates a Java source file from a KidCode Parse Tree.
 * It converts KidCode constructs (Decl, Assign, SayStmt, IfStmt, WhileStmt)
 * into valid Java syntax and writes them into a .java file.
 */
public class KidCodeGenerator {

    private ParseTreeNode root;
    private StringBuilder code = new StringBuilder();
 /**
     * Constructor
     * @param root Root of the Parse Tree generated by the Parser
     */
    public void KidCodeJavaFileGenerator(ParseTreeNode root) {
        this.root = root;
    }
    /**
     * Generates a Java file with the given file name.
     * @param fileName Name of the output .java file
     */
    public void generate(String fileName) throws IOException {
        
        // Start Java class structure
        code.append("public class GeneratedProgram {\n");
        code.append("    public static void main(String[] args) {\n\n");
        
        // Traverse parse tree and generate code
        visit(root);

        // Close class structure
        code.append("\n    }\n");
        code.append("}\n");
        
        // Write to file
        BufferedWriter writer = new BufferedWriter(new FileWriter(fileName));
        writer.write(code.toString());
        writer.close();
    }
    /**
     * Recursively visits Parse Tree nodes and generates Java code.
     * @param node Current parse tree node
     */
    private void visit(ParseTreeNode node) {
        if (node == null) return;

        String label = node.label;

                 // Declaration: NUMBER/NAME/FACT x = expr
        if (label.equals("Decl")) {
            String type = get(node.children.get(0));
            String id = get(node.children.get(1));
            String expr = eval(node.children.get(3));

            code.append("        ")
                .append(mapType(type)).append(" ")
                .append(id).append(" = ")
                .append(expr).append(";\n");
        }

        // Assignment: x = expr
        else if (label.equals("Assign")) {
            String id = get(node.children.get(0));
            String expr = eval(node.children.get(2));

            code.append("        ")
                .append(id).append(" = ")
                .append(expr).append(";\n");
        }

        // Say statement: SAY(expr)
        else if (label.equals("SayStmt")) {
            String expr = eval(node.children.get(2));

            code.append("        System.out.println(")
                .append(expr)
                .append(");\n");
        }

        // If statement
        else if (label.equals("IfStmt")) {
            String cond = eval(node.children.get(2));

            code.append("        if (")
                .append(cond)
                .append(") {\n");

            visit(node.children.get(5)); // StmtList

            code.append("        }\n");
        }

        // While loop
        else if (label.equals("WhileStmt")) {
            String cond = eval(node.children.get(2));

            code.append("        while (")
                .append(cond)
                .append(") {\n");

            visit(node.children.get(5)); // StmtList

            code.append("        }\n");
        }

        // Default: traverse children
        else {
            for (ParseTreeNode c : node.children) {
                visit(c);
            }
        }
    }

    /**
     * Evaluates expressions or terminals from parse tree.
     * @param node Expression node
     * @return String representation of expression
     */
    private String eval(ParseTreeNode node) {
        if (node == null) return "";

        String label = node.label;

        // Terminal values (Match: X)
        if (label.startsWith("Match: ")) {
            return label.replace("Match: ", "");
        }

        // Leaf node
        if (node.children.isEmpty()) {
            return label;
        }

        // Expression handling
        if (label.equals("Expr")) {
            if (node.children.size() == 1)
                return eval(node.children.get(0));

            String left = eval(node.children.get(0));
            String right = eval(node.children.get(1));
            return left + " + " + right;
        }

        return "";
    }

    /**
     * Extracts token value from node label.
     */
    private String get(ParseTreeNode node) {
        return node.label.replace("Match: ", "");
    }

    /**
     * Maps KidCode types to Java types.
     */
    private String mapType(String type) {
        switch (type) {
            case "NUMBER": return "int";
            case "FACT": return "boolean";
            case "NAME": return "String";
            default: return "int";
        }
    }
}
